## Gaussian PDF and CDF

In [1]:
from scipy.stats import norm

In [2]:
# find the probability of 0 from the std normal dist
norm.pdf(0)

0.3989422804014327

In [3]:
# also can modify mean and sd
# loc = mean
# scale = sd
norm.pdf(0, loc=5, scale=10)

0.03520653267642995

In [4]:
import numpy as np

In [8]:
# randomly pick 10 number from the std normal dist
r = np.random.randn(10)
r

array([-0.62592006,  2.0590978 ,  0.26211048,  0.22264532, -1.06215548,
        0.85963108,  1.06128572,  0.78597799,  1.0854857 , -0.61778809])

In [7]:
norm.pdf(r)

array([0.35482073, 0.39562312, 0.35320997, 0.3837615 , 0.36946499,
       0.38235674, 0.30568124, 0.19914849, 0.37579292, 0.20149189])

## Log pdf
Note log of joint pdf are faster

In [9]:
norm.logpdf(r)

array([-1.11482649, -3.0388804 , -0.95328948, -0.943724  , -1.48302566,
       -1.28842133, -1.48210222, -1.22781923, -1.50807814, -1.1097696 ])

## cdf

In [11]:
# cdf
norm.cdf(r)

array([0.26568369, 0.98025756, 0.60338187, 0.58809422, 0.14408255,
       0.80500378, 0.85571996, 0.78405981, 0.8611467 , 0.26835752])

In [12]:
# logcdf
norm.logcdf(r)

array([-1.32544882, -0.01993992, -0.50520501, -0.53086811, -1.93736886,
       -0.2169083 , -0.1558121 , -0.24326997, -0.1494904 , -1.31543517])

## Sampling from a Gaussian dist